# seo/weekly_seo.py — weekly GSC audit + content-opportunity report.
#
# Pulls Google Search Console and writes a markdown report covering: headline performance + WoW
# trend, top queries/pages, "striking-distance" queries (avg position 5-20 — one good post pushes
# them onto page 1), low-CTR high-impression pages (title/meta rewrite wins), and a ranked list of
# next-post topics drawn from REAL query demand. Degrades cleanly with a clear message if GSC isn't
# configured yet.
#
# Run:  .venv/Scripts/python -m seo.weekly_seo            (print to stdout)
#       .venv/Scripts/python -m seo.weekly_seo --out seo/reports/latest.md
# Render Cron Job command:  python -m seo.weekly_seo

import argparse
import sys
from datetime import date, timedelta

from seo import gsc


def _d(days_ago: int) -> str:
    return (date.today() - timedelta(days=days_ago)).isoformat()


def _agg(rows):
    c = sum(r.get("clicks", 0) for r in rows)
    i = sum(r.get("impressions", 0) for r in rows)
    return c, i, (c / i if i else 0.0)


def _table(rows, key_label, limit=15):
    out = [f"| {key_label} | Clicks | Impr. | CTR | Pos |", "|---|--:|--:|--:|--:|"]
    for r in rows[:limit]:
        k = (r.get("keys") or ["—"])[0]
        out.append(f"| {k} | {int(r.get('clicks',0))} | {int(r.get('impressions',0))} "
                   f"| {r.get('ctr',0)*100:.1f}% | {r.get('position',0):.1f} |")
    return "\n".join(out)


_QUESTION = ("how", "what", "why", "best", "vs", "tips", "guide", "drill", "improve", "fix")


def build_report(label, prop) -> str:
    end, start = _d(3), _d(31)            # GSC lags ~3 days; last 28-day window
    pend, pstart = _d(31), _d(59)          # prior 28-day window for trend

    cur = gsc.query(start=start, end=end, dimensions=("query",), row_limit=5000, site=prop)
    prev = gsc.query(start=pstart, end=pend, dimensions=("query",), row_limit=5000, site=prop)
    pages = gsc.query(start=start, end=end, dimensions=("page",), row_limit=2000, site=prop)

    cc, ci, cctr = _agg(cur)
    pc, pi, _ = _agg(prev)

    def delta(now, was):
        if not was:
            return "—" if not now else "new"
        return f"{(now-was)/was*100:+.0f}%"

    # Striking distance: position 5-20, ranked by impressions (biggest near-win first).
    strike = sorted([r for r in cur if 5 <= r.get("position", 99) <= 20],
                    key=lambda r: -r.get("impressions", 0))
    # Low-CTR opportunity: lots of impressions, weak CTR, not already top-3.
    lowctr = sorted([r for r in cur if r.get("impressions", 0) >= 30
                     and r.get("ctr", 1) < 0.02 and r.get("position", 0) > 3],
                    key=lambda r: -r.get("impressions", 0))
    # Topic ideas: striking-distance, question-shaped queries first.
    ideas = [r for r in strike if any(w in (r.get("keys") or [""])[0].lower() for w in _QUESTION)]
    ideas += [r for r in strike if r not in ideas]

    top_clicks = sorted(cur, key=lambda r: -r.get("clicks", 0))

    L = []
    L.append(f"# {label} — Weekly SEO report (Google Search Console)")
    L.append(f"\n**Window:** {start} → {end} (vs prior 28 days). Source: GSC — real data.\n")
    L.append("## At a glance")
    L.append(f"- **Clicks:** {int(cc)} ({delta(cc, pc)} WoW)")
    L.append(f"- **Impressions:** {int(ci)} ({delta(ci, pi)} WoW)")
    L.append(f"- **Avg CTR:** {cctr*100:.1f}%")
    L.append(f"- **Queries you appear for:** {len(cur)}\n")

    L.append("## Next-post opportunities (striking distance — real demand, position 5–20)")
    L.append("Write a focused post on one of these and you push from page-2 onto page-1:\n")
    L.append(_table(ideas, "Query (topic idea)", limit=12) if ideas
             else "_No striking-distance queries yet — keep publishing to build impressions._")

    L.append("\n## Title/meta rewrite wins (high impressions, low CTR)")
    L.append(_table(lowctr, "Query", limit=10) if lowctr
             else "_No clear low-CTR outliers this week._")

    L.append("\n## Top queries by clicks")
    L.append(_table(top_clicks, "Query", limit=15))

    L.append("\n## Top pages")
    page_rows = sorted(pages, key=lambda r: -r.get("clicks", 0))
    L.append(_table(page_rows, "Page", limit=15))

    L.append("\n---\n_Generated by seo/weekly_seo.py from Google Search Console._")
    return "\n".join(L)


def _label_from_property(prop: str) -> str:
    label = prop.split(":", 1)[1] if prop.startswith("sc-domain:") else prop
    return label.replace("https://", "").replace("http://", "").replace("www.", "").strip("/")


def _targets(args):
    """Resolve (slug, label, property) tuples to audit. --all = every site in seo/sites.py;
    --site <slug> = one registered site; otherwise the single GSC_SITE_URL env (back-comat)."""
    from seo import sites
    if args.all:
        return [(s.slug, s.label, s.gsc_property) for s in sites.all_sites()]
    if args.site:
        s = sites.get(args.site)
        if not s:
            raise SystemExit(f"unknown site '{args.site}'. Known: "
                             + ", ".join(x.slug for x in sites.all_sites()))
        return [(s.slug, s.label, s.gsc_property)]
    prop = gsc.site_url()  # raises GSCNotConfigured if GSC_SITE_URL unset
    return [("report", _label_from_property(prop), prop)]


def main(argv=None):
    ap = argparse.ArgumentParser(description="Weekly GSC SEO report (single or multi-site)")
    ap.add_argument("--site", help="audit one registered site by slug (see seo/sites.py)")
    ap.add_argument("--all", action="store_true", help="audit every site in seo/sites.py")
    ap.add_argument("--out", help="write report(s) here — a file for one site, a directory for --all")
    args = ap.parse_args(argv)
    try:  # Windows consoles default to cp1252 and choke on report glyphs (→, etc.)
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    if not gsc.auth_ready():
        print("GSC not configured: set the OAuth env vars (GSC_OAUTH_CLIENT_ID/SECRET/"
              "REFRESH_TOKEN) — see seo/README.md.", file=sys.stderr)
        return 2

    try:
        targets = _targets(args)
    except gsc.GSCNotConfigured as e:
        print(f"GSC not configured: {e}", file=sys.stderr)
        return 2

    import os
    results = []
    for slug, label, prop in targets:
        try:
            results.append((slug, label, build_report(label, prop)))
        except Exception as e:  # one site failing must not kill the rest of the run
            results.append((slug, label, f"# {label}\n\n> Report failed: {e}\n"))

    if args.out and len(results) > 1:                 # --out is a directory for multi-site
        os.makedirs(args.out, exist_ok=True)
        for slug, _, report in results:
            path = os.path.join(args.out, f"{slug}.md")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(report)
            print(f"wrote {path}")
    elif args.out:                                     # single report to a file
        os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(results[0][2])
        print(f"wrote {args.out}")
    else:
        print(("\n\n" + "=" * 78 + "\n\n").join(r for _, _, r in results))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
