# seo/weekly_seo.py — weekly GSC audit + content-opportunity report.
#
# Pulls Google Search Console and writes a markdown report covering: headline performance + WoW
# trend, top queries/pages, "striking-distance" queries (avg position 5-20 — one good post pushes
# them onto page 1), low-CTR high-impression pages (title/meta rewrite wins), and a ranked list of
# next-post topics drawn from REAL query demand. Degrades cleanly with a clear message if GSC isn't
# configured yet.
#
# Run:  .venv/Scripts/python -m seo.weekly_seo            (print to stdout)
#       .venv/Scripts/python -m seo.weekly_seo --out seo/reports/latest.md
# Render Cron Job command:  python -m seo.weekly_seo

import argparse
import sys
from datetime import date, timedelta

from seo import gsc


def _d(days_ago: int) -> str:
    return (date.today() - timedelta(days=days_ago)).isoformat()


def _agg(rows):
    c = sum(r.get("clicks", 0) for r in rows)
    i = sum(r.get("impressions", 0) for r in rows)
    return c, i, (c / i if i else 0.0)


def _table(rows, key_label, limit=15):
    out = [f"| {key_label} | Clicks | Impr. | CTR | Pos |", "|---|--:|--:|--:|--:|"]
    for r in rows[:limit]:
        k = (r.get("keys") or ["—"])[0]
        out.append(f"| {k} | {int(r.get('clicks',0))} | {int(r.get('impressions',0))} "
                   f"| {r.get('ctr',0)*100:.1f}% | {r.get('position',0):.1f} |")
    return "\n".join(out)


_QUESTION = ("how", "what", "why", "best", "vs", "tips", "guide", "drill", "improve", "fix")


def build_report() -> str:
    if not gsc.configured():
        return ("# Weekly SEO report\n\n> **GSC not configured.** Set `GSC_SERVICE_ACCOUNT_JSON` "
                "and `GSC_SITE_URL` in the Render dashboard (see seo/README.md), then re-run.\n")

    end, start = _d(3), _d(31)            # GSC lags ~3 days; last 28-day window
    pend, pstart = _d(31), _d(59)          # prior 28-day window for trend

    cur = gsc.query(start=start, end=end, dimensions=("query",), row_limit=5000)
    prev = gsc.query(start=pstart, end=pend, dimensions=("query",), row_limit=5000)
    pages = gsc.query(start=start, end=end, dimensions=("page",), row_limit=2000)

    cc, ci, cctr = _agg(cur)
    pc, pi, _ = _agg(prev)

    def delta(now, was):
        if not was:
            return "—" if not now else "new"
        return f"{(now-was)/was*100:+.0f}%"

    # Striking distance: position 5-20, ranked by impressions (biggest near-win first).
    strike = sorted([r for r in cur if 5 <= r.get("position", 99) <= 20],
                    key=lambda r: -r.get("impressions", 0))
    # Low-CTR opportunity: lots of impressions, weak CTR, not already top-3.
    lowctr = sorted([r for r in cur if r.get("impressions", 0) >= 30
                     and r.get("ctr", 1) < 0.02 and r.get("position", 0) > 3],
                    key=lambda r: -r.get("impressions", 0))
    # Topic ideas: striking-distance, question-shaped queries first.
    ideas = [r for r in strike if any(w in (r.get("keys") or [""])[0].lower() for w in _QUESTION)]
    ideas += [r for r in strike if r not in ideas]

    top_clicks = sorted(cur, key=lambda r: -r.get("clicks", 0))

    L = []
    L.append("# Ten-Fifty5 — Weekly SEO report (Google Search Console)")
    L.append(f"\n**Window:** {start} → {end} (vs prior 28 days). Source: GSC — real data.\n")
    L.append("## At a glance")
    L.append(f"- **Clicks:** {int(cc)} ({delta(cc, pc)} WoW)")
    L.append(f"- **Impressions:** {int(ci)} ({delta(ci, pi)} WoW)")
    L.append(f"- **Avg CTR:** {cctr*100:.1f}%")
    L.append(f"- **Queries you appear for:** {len(cur)}\n")

    L.append("## Next-post opportunities (striking distance — real demand, position 5–20)")
    L.append("Write a focused post on one of these and you push from page-2 onto page-1:\n")
    L.append(_table(ideas, "Query (topic idea)", limit=12) if ideas
             else "_No striking-distance queries yet — keep publishing to build impressions._")

    L.append("\n## Title/meta rewrite wins (high impressions, low CTR)")
    L.append(_table(lowctr, "Query", limit=10) if lowctr
             else "_No clear low-CTR outliers this week._")

    L.append("\n## Top queries by clicks")
    L.append(_table(top_clicks, "Query", limit=15))

    L.append("\n## Top pages")
    page_rows = sorted(pages, key=lambda r: -r.get("clicks", 0))
    L.append(_table(page_rows, "Page", limit=15))

    L.append("\n---\n_Generated by seo/weekly_seo.py from Google Search Console._")
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Weekly GSC SEO report")
    ap.add_argument("--out", help="write the markdown report to this path (else stdout)")
    args = ap.parse_args(argv)
    try:
        report = build_report()
    except gsc.GSCNotConfigured as e:
        print(f"GSC not configured: {e}", file=sys.stderr)
        return 2
    if args.out:
        import os
        os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(report)
        print(f"wrote {args.out}")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
